# File: waterFitter.mac
# Brief: Short macro showing how to run the waterFitter
#
# Date: 19-05-2014
# Contact: Dr M Mottram, <m.mottram@qmul.ac.uk>
# Revisions:
#       19-05-2014 I. Coulter <icoulter@hep.upenn.edu> Initial commit.
#
# This is a macro which shows how to run the waterFitter, which gives
# the "best" fit for the water phase, as defined by the reconstruction
# group. Details of what this contains can be found in the user manual
# or within the code itself.
#

# Load a water phase geometry
/rat/db/set DETECTOR geo_file "geo/snoplus_water.geo"

/run/initialize

# BEGIN EVENT LOOP
/rat/proc frontend
/rat/proc trigger
/rat/proc eventbuilder
/rat/proc count
/rat/procset update 10
/rat/proc calibratePMT

# Run the waterFitter
/rat/proc waterFitter

/rat/proclast outroot
/rat/procset file "output.ntuple.root"
# END EVENTLOOP

/generator/add combo gun:fill
/generator/vtx/set e- 0 0 0 5.0
/generator/pos/set 0 0 0
/generator/rate/set 1

/rat/run/start
exit
